login/models.py
from flask_login import UserMixin
from werkzeug.security import generate_password_hash, check_password_hash
from datetime import datetime
from hashlib import md5

from main import db, login_manager

"""
用户表相关model

登录验证需要实现验证接口
提供了一个默认实现UserMixin ：
is_authenticated 方法有一个具有迷惑性的名称。一般而言，这个方法应该只返回 True，除非表示用户的对象因为某些原因不允许被认证。
is_active 方法应该返回 True，除非是用户是无效的，比如因为他们的账号是被禁止。
is_anonymous 方法应该返回 True，如果是匿名的用户不允许登录系统。
"""


class User(UserMixin, db.Model):
    __tablename__ = 'user'
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(64), index=True, unique=True)
    email = db.Column(db.String(120), index=True, unique=True)
    password_hash = db.Column(db.String(128))
    about_me = db.Column(db.String(140))
    last_seen = db.Column(db.DateTime, default=datetime.utcnow)
    # back是反向引用,User和Post是一对多的关系，backref是表示在Post中新建一个
    # 属性author，关联的是Post中的user_id外键关联的User对象。lazy属性常用的值
    # 的含义，select就是访问到属性的时候，就会全部加载该属性的数据;joined则是
    # 在对关联的两个表进行join操作，从而获取到所有相关的对象;
    # dynamic则不一样，在访问属性的时候，并没有在内存中加载数据，而是返回一个
    # query对象, 需要执行相应方法才可以获取对象，比如.all()
    posts = db.relationship('Post', backref='author', lazy='dynamic')

    # 设置密码
    def set_password(self, password):
        self.password_hash = generate_password_hash(password)

    # 验证密码
    def check_password(self, password):
        return check_password_hash(self.password_hash, password)

    # 获取头像
    def avatar(self, size):
        digest = md5(self.email.lower().encode('utf-8')).hexdigest()
        return 'https://www.gravatar.com/avatar/{}?d=identicon&s={}'.format(
            digest, size)

    def __repr__(self):
        return '<用户名:{}>'.format(self.username)


# 不使用默认实现UserMixin，需要实现所有方法
# class User(db.Model):
#     id = db.Column(db.Integer, primary_key=True)
#     nickname = db.Column(db.String(64), index=True, unique=True)
#     email = db.Column(db.String(120), index=True, unique=True)
#     posts = db.relationship('Post', backref='author', lazy='dynamic')
#
#     @property
#     def is_authenticated(self):
#         return True
#
#     @property
#     def is_active(self):
#         return True
#
#     @property
#     def is_anonymous(self):
#         return False
#
#     # get_id 方法应该返回一个用户唯一的标识符，以 unicode 格式。我们使用
#     # 数据库生成的唯一的 id。需要注意地是在 Python 2 和 3 之间由于 unicode
#     # 处理的方式的不同我们提供了相应的方式。
#     def get_id(self):
#         try:
#             return unicode(self.id)  # python 2
#         except NameError:
#             return str(self.id)  # python 3
#
#     def __repr__(self):
#         return '<User %r>' % (self.nickname)

# 用于从数据库加载用户。这个函数将会被 Flask-Login 使用
@login_manager.user_loader
def load_user(id):
    # 在 Flask-Login 中的用户 id 永远是 unicode 字符串，因此在我们
    # 把 id 发送给 Flask-SQLAlchemy 之前，把 id 转成整型是必须的，否则会报错！
    return User.query.get(int(id))


class Post(db.Model):
    __tablename__ = 'post'
    id = db.Column(db.INTEGER, primary_key=True)
    body = db.Column(db.String(140))
    timestamp = db.Column(db.DateTime, index=True, default=datetime.utcnow())
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))

    def __repr__(self):
        return '<Post{}>'.format(self.body)

login/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, BooleanField, SubmitField
from wtforms.validators import DataRequired, ValidationError, Email, EqualTo

from login.models import User

# 表单中实际的字段也将会被表单对象渲染，你只必须在字段应该被插入的地方
# 指明一个 {{form.field_name}} 模板参数
class LoginForm(FlaskForm):
    # DataRequired，当你在当前表格没有输入而直接到下一个表格时会提示你输入
    username = StringField('用户名', validators=[DataRequired(message='请输入名户名')])
    password = PasswordField('密码', validators=[DataRequired(message='请输入密码')])
    remember_me = BooleanField('记住我')
    submit = SubmitField('登录')


class RegistrationForm(FlaskForm):
    username = StringField('用户名', validators=[DataRequired(message='请输入用户名')])
    email = StringField('邮箱', validators=[DataRequired(message='请输入邮箱'), Email()])
    password = PasswordField('密码', validators=[DataRequired(message='请输入密码')])
    password2 = PasswordField(
        '重复密码', validators=[DataRequired(message='请再次输入密码'), EqualTo('password')])
    submit = SubmitField('注册')

    # 校验用户名是否重复
    def validate_username(self, username):
        user = User.query.filter_by(username=username.data).first()
        if user is not None:
            raise ValidationError('用户名重复了，请您重新换一个呗!')

    # 校验邮箱是否重复
    def validate_email(self, email):
        user = User.query.filter_by(email=email.data).first()
        if user is not None:
            raise ValidationError('邮箱重复了，请您重新换一个呗!')

login/__init__.py
from flask import Blueprint

login_opt = Blueprint('login_opt', __name__, static_folder="../static", template_folder="../templates")

from login import routes, models, forms

login/routes.py
#!/usr/bin/python3
# encoding: utf-8
from flask import flash, redirect, url_for, request, render_template
from flask_login import current_user, login_user, logout_user

from login import login_opt
from login.forms import LoginForm, RegistrationForm
from login.models import User
from main import db


@login_opt.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('index'))

    form = LoginForm()
    '''
    validate_on_submit
    方法做了所有表单处理工作。当表单正在展示给用户的时候调用它，它会返回False.
    如果validate_on_submit在表单提交请求中被调用，它将会收集所有的数据，对字段
    进行验证，如果所有的事情都通过的话，它将会返回True，表示数据都是合法的。
    '''
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if user is None or not user.check_password(form.password.data):
            flash('无效用户名或密码')
            return redirect(url_for('login_opt.login'))
        login_user(user, remember=form.remember_me.data)
        next_page = request.args.get('next')
        if not next_page or url_for(next_page).netloc != '':
            next_page = url_for('index')
        return redirect(next_page)
    return render_template('login.html', title='Login', form=form)


@login_opt.route('/logout')
def logout():
    logout_user()  # 调用自带utils的退出登录逻辑
    return redirect(url_for('index'))


@login_opt.route('/register', methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('index'))
    form = RegistrationForm()
    if form.validate_on_submit():
        user = User(username=form.username.data, email=form.email.data)
        user.set_password(form.password.data)
        db.session.add(user)
        db.session.commit()
        flash('恭喜你成为我们网站的新用户')
        return redirect(url_for('login_opt.login'))
    return render_template('register.html', title='注册', form=form)

templates/_post.html
<table>
    <tr valign="top">
        <td><img src="{{ post.author.avatar(36) }}"></td>
        <td>{{ post.author.username }} 说:<br>{{ post.body }}</td>
    </tr>
</table>

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% if title %}
        <title>{{ title }}</title>
    {% else %}
        <title>欢迎来到Flask例子程序</title>
    {% endif %}
    <link rel="stylesheet" href="../static/head.css">
    {% block head %}
        {#头部内容#}
    {% endblock %}
</head>
<body>
<div class="head">
    博客：<a href="{{ url_for('index') }}">首页</a>
    {% if current_user.is_anonymous %}
        <a href="{{ url_for('login_opt.login') }}">登录</a>
    {% else %}
        <a href="{{ url_for('about_opt.user', username=current_user.username) }}">用户中心</a>
        <a href="{{ url_for('login_opt.logout') }}">退出</a>
    {% endif %}
</div>
<hr>
{% with messages = get_flashed_messages() %}
    {% if messages %}
        <ur>
            {% for mesage in messages %}
                <li>{{ mesage }}</li>
            {% endfor %}
        </ur>
    {% endif %}
{% endwith %}
{% block content %}
    {#页面内容#}
{% endblock %}
{% block foot %}
    {#页尾内容#}
{% endblock %}
</body>
</html>

templates/edit_profile.html
{% extends "base.html" %}

{% block content %}
    <h1>个人资料编辑</h1>
    <form action="" method="post">
        {{ form.hidden_tag() }}
        <p>
            {{ form.username.label }}<br>
            {{ form.username(size=32) }}<br>
            {% for error in form.username.errors %}
                <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>
            {{ form.about_me.label }}<br>
            {{ form.about_me(cols=50, rows=4) }}<br>
            {% for error in form.about_me.errors %}
                <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>{{ form.submit() }}</p>
    </form>
{% endblock %}

templates/index.html
{% extends 'base.html' %}
{% block content %}
    <h1>你好呀, {{ current_user.username }} !</h1>
    {% for post in posts %}
        <div><p>{{ post.author.username }} 说:<b>{{ post.body }}</b></p></div>
    {% endfor %}
{% endblock %}

templates/login.html
{% extends 'base.html' %}

{% block content %}
    <h1>登 录</h1>
    <p>还没注册? <a href="{{ url_for('login_opt.register') }}">点击一下就可以注册哦!</a></p>
    <form action="" method="post">
        {# form.hidden_tag() 模板参数将被替换为一个隐藏字段，用来是实现在配置中
        激活的 CSRF 保护。如果你已经激活了 CSRF，这个字段需要出现在你所有的表单中。#}
        {{ form.hidden_tag() }}
        <p>
            {{ form.username.label }}<br>
            {{ form.username(size=32) }}<br>
            {# 任何需要验证的字段都会把错误信息放入 form.field_name.errors 下#}
            {% for error in form.username.errors %}
                <span style="color: red;">[{{ error }}]</span>
            {% endfor %}

        </p>
        <p>
            {{ form.password.label }}<br>
            {{ form.password(size=32) }}<br>
            {% for error in form.password.errors %}
                <span style="color: red;">[{{ error }}]</span>
            {% endfor %}

        </p>
        <p>{{ form.remember_me() }} {{ form.remember_me.label }}</p>
        <p>{{ form.submit() }}</p>
    </form>
{% endblock %}

templates/register.html
{% extends "base.html" %}
{% block head %}
    <link rel="stylesheet" href="../static/register.css">
{% endblock %}
{% block content %}
    <h1>注册</h1>
    <form action="" method="post">
        {{ form.hidden_tag() }}
        <p>
            {{ form.username.label }}<br>
            {{ form.username(size=32) }}<br>
            {% for error in form.username.errors %}
                <span class="error-text">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>
            {{ form.email.label }}<br>
            {{ form.email(size=64) }}<br>
            {% for error in form.email.errors %}
                <span class="error-text">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>
            {{ form.password.label }}<br>
            {{ form.password(size=32) }}<br>
            {% for error in form.password.errors %}
                <span class="error-text">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>
            {{ form.password2.label }}<br>
            {{ form.password2(size=32) }}<br>
            {% for error in form.password2.errors %}
                <span class="error-text">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>{{ form.submit() }}</p>
    </form>
{% endblock %}

templates/user.html
{% extends "base.html" %}

{% block content %}
    <table>
        <tr valign="top">
            <td><img src="{{ user.avatar(128) }}"></td>
            <td><h1>User: {{ user.username }}</h1></td>
            {% if user.about_me %}<p>{{ user.about_me }}</p>{% endif %}
            {% if user.last_seen %}<p>最近登录: {{ user.last_seen }}</p>{% endif %}
            {% if user == current_user %}
                <p><a href="{{ url_for('about_opt.edit_profile') }}">个人资料编辑</a></p>
            {% endif %}
        </tr>
    </table>
    <hr>
    {% for post in posts %}
        {% include '_post.html' %}
    {% endfor %}
{% endblock %}